# Build customization
builds:
  - binary: gotemplate
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ignore:
      # Windows arm64 is not used and does not compile well as of writing
      - goos: windows
        goarch: arm64

# Build one binary for Mac OS (arm64 and amd64)
universal_binaries:
  - replace: true

# Archive customization
archives:
  - format: zip
    files:
      - nothing.*

# GitHub release customization
release:
  prerelease: auto
