#! /usr/bin/env bash 

for file in docs/doc_test/*.md
do
    gotemplate -dP $file > ${file%.*}.razor
    gotemplate -P $file > ${file%.*}.rendered
done


DOC_FOLDER="docs"

mkdir -p $DOC_FOLDER

# Generate function info
echo """\`\`\`text
$(gotemplate list --no-extension -c)
\`\`\`""" &> $DOC_FOLDER/_functions.md

# Generate usage info
echo """\`\`\`text
$(gotemplate --help-long)
\`\`\`""" &> $DOC_FOLDER/_usage.md

# Generate detailed function info
echo """{% include navigation.html %}
## Functions
\`\`\`text
$(gotemplate list --no-extension -l)
\`\`\`""" &> $DOC_FOLDER/functions_long.md